[package]
name = 'router'
version = '1.0.0'

[addresses]
aptos_names = "_"
aptos_names_v2_1 = "_"
aptos_names_admin = "_"
aptos_names_funds = "_"
router_signer = "_"
router = "_"

[dev-addresses]
aptos_names = "0x867ed1f6bf916171b1de3ee92849b8978b7d1b9e0a8cc982a3d19d535dfd9c0c"
aptos_names_v2_1 = "0x867ed1f6bf916171b1de3ee92849b8978b7d1b9e0a8cc982a3d19d535dfd9c0c"
aptos_names_admin = "0x91945b4672607a327019e768dd6045d1254d1102d882df434ca734250bb3581d"
aptos_names_funds = "0x78ee3915e67ef5d19fa91d1e05e60ae08751efd12ce58e23fc1109de87ea7865"
router_signer = "0x673edba0e0b864ca3eb458fdd45d55f6eced59bb5bdc3b1f3671fae0f9ea4e4d"
router = "0x6FF"


[dependencies.aptos_names]
local = "../core"

[dependencies.aptos_names_v2_1]
local = "../core_v2"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-framework.git'
rev = 'mainnet'
subdir = 'aptos-framework'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-framework.git'
rev = 'mainnet'
subdir = 'aptos-token'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-framework.git'
rev = 'mainnet'
subdir = 'aptos-token-objects'
