[package]
name = 'bulk_migrate'
version = '1.0.0'

[addresses]
bulk_migrate = "0xb27f7d329f6d2c8867e5472958c3cfabc781300ca9649f244e267e1d6b966c94"

[dependencies.aptos_names_v2]
local = "../core_v2"

[dependencies.router]
local = "../router"
