script {
    use std::option;
    use aptos_framework::timestamp;

    const SECONDS_PER_YEAR: u64 = 60 * 60 * 24 * 365;

    fun main(admin: &signer) {
        let names = vector [
            b"aptin",
            b"aries",
            b"bluemove",
            b"fewcha",
            b"momentumsafe",
            b"msafe",
            b"notifi",
            b"switchboard",
            b"huobi",
            b"wormhole",
            b"hamlet",
            b"hc-xie",
            b"hcxie",
            b"jake",
            b"skinner",
            b"6mv",
            b"animoca",
            b"balajis",
            b"dudas",
            b"hashed",
            b"nural",
            b"parafi",
            b"superscrypt",
            b"variant",
            b"kraken",
            b"blocktower",
            b"gemini",
            b"pyth",
            b"scotney",
            b"scott",
            b"scottnelson",
            b"oak",
            b"anchorage",
            b"argo",
            b"hippo",
            b"nutrios",
            b"okx",
            b"trust",
            b"layerzero",
            b"alexherrera",
            b"gani",
            b"maria",
            b"mariacamila",
            b"tjandrasuwita",
            b"dragonfly",
            b"griffingaming",
            b"irongrey",
            b"paxos",
            b"santiago",
            b"coinbase",
            b"houstonswap",
            b"naval",
            b"scribble",
            b"franklintempleton",
            b"a16z",
            b"apollo",
            b"brevanhoward",
            b"hybe",
            b"multicoin",
            b"paypal",
            b"haun",
            b"temasek",
            b"circle",
            b"binance",
            b"superposition",
            b"upbit",
            b"google",
            b"ans",
            b"aptos-foundation",
            b"aptos-labs",
            b"aptos-name-service",
            b"aptos-names-service",
            b"aptos-names",
            b"aptos",
            b"aptosfoundation",
            b"aptoslabs",
            b"aptosnames",
            b"aptosnameservice",
            b"aptosnamesservice",
            b"faucet",
            b"foundation",
            b"gas",
            b"move-lang",
            b"move-language",
            b"move",
            b"null",
            b"octa",
            b"petra-foundation",
            b"petra",
            b"petrafoundation",
            b"petrawallet",
            b"undefined",
            b"validators",
            b"aching",
            b"avery",
            b"averyching",
            b"brayden",
            b"ching",
            b"kay",
            b"moalishaikh",
            b"mohammadshaikh",
            b"moshaikh",
            b"moshaikhs",
            b"paxton",
            b"rakim",
            b"schuyler",
            b"schuylershaikh",
            b"schuylerwoods",
            b"weston",
            b"crypto",
            b"cryptography",
            b"dao",
            b"defi",
            b"eth",
            b"wallet",
            b"xyz",
        ];
        let years_to_expire = 100;

        while (!std::vector::is_empty(&names)) {
            let name = std::string::utf8(std::vector::pop_back(&mut names));
            aptos_names_v2_1::v2_1_domains::force_set_name_expiration(
                admin,
                name,
                option::none(),
                timestamp::now_seconds() + SECONDS_PER_YEAR * years_to_expire,
            )
        }
    }
}
