[package]
name = 'aptos_names_register'
version = '1.0.0'

[addresses]
repository = "0xb27f7d329f6d2c8867e5472958c3cfabc781300ca9649f244e267e1d6b966c94"

[dev-addresses]
aptos_names = "0x5555000"
aptos_names_admin = "0x5555002"
aptos_names_funds = "0x5555003"
router_signer = "0x5555004"


[dependencies.aptos_names]
local = "../core"
