[package]
name = 'aptos_names_transfer'
version = '1.0.0'

[addresses]
aptos_names = "_"
aptos_names_admin = "_"
aptos_names_funds = "_"
router_signer = "_"

[dev-addresses]
aptos_names = "0x1FF"
aptos_names_admin = "0x3FF"
aptos_names_funds = "0x4FF"
router_signer = "0x2FF"

[dependencies.aptos_names]
local = "../core"
