[package]
name = 'aptos_names_v2'
version = '1.0.0'

[addresses]
aptos_names_v2 = "0x123"
aptos_names_admin = "0x234"
aptos_names_funds = "0x345"

[dependencies.aptos_names]
local = "../core"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'
